/**
 * Default village list for searchable selection (admin + group flows).
 * Users can still enter any other village name not in this list.
 */
export const STATIC_VILLAGES = [
    "TIWADIA",
    "PIPALPATI",
    "UDAINAGAR",
    "DHOBGHATTA",
    "IMLIPURA",
    "SHYAMPURA",
    "MAHIGAON",
    "DEOJHIRI",
    "NEEMANPURA",
    "JOJAKPURA",
    "SEWANPANI",
    "MAGARADEH",
    "POLAKHAL",
    "AGRABUZURG",
    "RAMPURA",
    "KATKYA",
    "AGRAKHURD",
    "SOVALYAPURA",
    "NARSINGPURA",
    "SEMLIKHEDA",
    "GURARDA",
    "MAWADIPURA",
    "PANDUTALAB",
    "KISHANGARH",
    "TANTUKHEDI",
    "PEEPARI",
    "MIRZAPUR",
    "DHARDITALAB",
    "PATADIPALA",
    "RATANPUR",
    "POTLA",
    "PIPALYA LOHAD",
    "DEONALYA",
    "ANANDNAGAR",
    "HARAMBADI",
    "BAWADIKHEDA",
    "SITAPURI",
    "JAMLI",
    "BISALI",
    "KANDYA",
    "PATPADI",
    "SIRALIBID",
    "BORKHEDI",
    "JAMASINDH",
    "SABALGARH",
    "HIRAPUR",
    "KHUTKHAL",
    "UDAIPURA",
    "KANAD",
    "KOTHMEER",
    "KOTKHEDI",
    "NACHANBOR",
].sort((a, b) => a.localeCompare(b, "en-IN"));
